namespace HP3
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation2 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            this.mainLeftPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.mainLblUserName = new Bunifu.UI.WinForms.BunifuLabel();
            this.mainBttAcerca = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mainBttSeguridad = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mainBttFacturacion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.indicator = new System.Windows.Forms.PictureBox();
            this.mainBttTablas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.mainBttExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mainPages = new Bunifu.UI.WinForms.BunifuPages();
            this.tabAcerca = new System.Windows.Forms.TabPage();
            this.tabSeguridad = new System.Windows.Forms.TabPage();
            this.tabFacturacion = new System.Windows.Forms.TabPage();
            this.tabTablas = new System.Windows.Forms.TabPage();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tablasBttCategorias = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tablasBttProductos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tablasBttClientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tablasPages = new Bunifu.UI.WinForms.BunifuPages();
            this.tabClientes = new System.Windows.Forms.TabPage();
            this.tabProductos = new System.Windows.Forms.TabPage();
            this.tabCategorias = new System.Windows.Forms.TabPage();
            this.mainLeftPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.indicator)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.mainPages.SuspendLayout();
            this.tabTablas.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.tablasPages.SuspendLayout();
            this.SuspendLayout();
            // 
            // mainLeftPanel
            // 
            this.mainLeftPanel.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainLeftPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainLeftPanel.BackgroundImage")));
            this.mainLeftPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.mainLeftPanel.BorderColor = System.Drawing.Color.Transparent;
            this.mainLeftPanel.BorderRadius = 0;
            this.mainLeftPanel.BorderThickness = 0;
            this.mainLeftPanel.Controls.Add(this.mainBttExit);
            this.mainLeftPanel.Controls.Add(this.mainLblUserName);
            this.mainLeftPanel.Controls.Add(this.mainBttAcerca);
            this.mainLeftPanel.Controls.Add(this.mainBttSeguridad);
            this.mainLeftPanel.Controls.Add(this.mainBttFacturacion);
            this.mainLeftPanel.Controls.Add(this.indicator);
            this.mainLeftPanel.Controls.Add(this.mainBttTablas);
            this.mainLeftPanel.Controls.Add(this.bunifuPictureBox1);
            this.mainLeftPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.mainLeftPanel.Location = new System.Drawing.Point(0, 0);
            this.mainLeftPanel.Name = "mainLeftPanel";
            this.mainLeftPanel.ShowBorders = false;
            this.mainLeftPanel.Size = new System.Drawing.Size(185, 511);
            this.mainLeftPanel.TabIndex = 0;
            // 
            // mainLblUserName
            // 
            this.mainLblUserName.AllowParentOverrides = false;
            this.mainLblUserName.AutoEllipsis = false;
            this.mainLblUserName.Cursor = System.Windows.Forms.Cursors.Default;
            this.mainLblUserName.CursorType = System.Windows.Forms.Cursors.Default;
            this.mainLblUserName.Font = new System.Drawing.Font("Urbanist", 18F);
            this.mainLblUserName.ForeColor = System.Drawing.SystemColors.Control;
            this.mainLblUserName.Location = new System.Drawing.Point(37, 149);
            this.mainLblUserName.Name = "mainLblUserName";
            this.mainLblUserName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.mainLblUserName.Size = new System.Drawing.Size(111, 31);
            this.mainLblUserName.TabIndex = 6;
            this.mainLblUserName.Text = "UserName";
            this.mainLblUserName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.mainLblUserName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // mainBttAcerca
            // 
            this.mainBttAcerca.AllowAnimations = true;
            this.mainBttAcerca.AllowMouseEffects = true;
            this.mainBttAcerca.AllowToggling = true;
            this.mainBttAcerca.AnimationSpeed = 200;
            this.mainBttAcerca.AutoGenerateColors = false;
            this.mainBttAcerca.AutoRoundBorders = false;
            this.mainBttAcerca.AutoSizeLeftIcon = true;
            this.mainBttAcerca.AutoSizeRightIcon = true;
            this.mainBttAcerca.BackColor = System.Drawing.Color.Transparent;
            this.mainBttAcerca.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainBttAcerca.BackgroundImage")));
            this.mainBttAcerca.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttAcerca.ButtonText = "Acerca";
            this.mainBttAcerca.ButtonTextMarginLeft = 0;
            this.mainBttAcerca.ColorContrastOnClick = 45;
            this.mainBttAcerca.ColorContrastOnHover = 45;
            this.mainBttAcerca.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = false;
            borderEdges2.BottomRight = false;
            borderEdges2.TopLeft = false;
            borderEdges2.TopRight = false;
            this.mainBttAcerca.CustomizableEdges = borderEdges2;
            this.mainBttAcerca.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mainBttAcerca.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttAcerca.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttAcerca.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttAcerca.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mainBttAcerca.Font = new System.Drawing.Font("Urbanist Medium", 13F);
            this.mainBttAcerca.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttAcerca.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttAcerca.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.mainBttAcerca.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.mainBttAcerca.IconMarginLeft = 11;
            this.mainBttAcerca.IconPadding = 8;
            this.mainBttAcerca.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mainBttAcerca.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mainBttAcerca.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mainBttAcerca.IconSize = 25;
            this.mainBttAcerca.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.IdleBorderRadius = 1;
            this.mainBttAcerca.IdleBorderThickness = 1;
            this.mainBttAcerca.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.IdleIconLeftImage = global::HP3.Properties.Resources.icoInfoWhite;
            this.mainBttAcerca.IdleIconRightImage = null;
            this.mainBttAcerca.IndicateFocus = false;
            this.mainBttAcerca.Location = new System.Drawing.Point(0, 344);
            this.mainBttAcerca.Name = "mainBttAcerca";
            this.mainBttAcerca.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttAcerca.OnDisabledState.BorderRadius = 1;
            this.mainBttAcerca.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttAcerca.OnDisabledState.BorderThickness = 0;
            this.mainBttAcerca.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttAcerca.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttAcerca.OnDisabledState.IconLeftImage = null;
            this.mainBttAcerca.OnDisabledState.IconRightImage = null;
            this.mainBttAcerca.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.onHoverState.BorderRadius = 1;
            this.mainBttAcerca.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttAcerca.onHoverState.BorderThickness = 0;
            this.mainBttAcerca.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttAcerca.onHoverState.IconLeftImage = null;
            this.mainBttAcerca.onHoverState.IconRightImage = null;
            this.mainBttAcerca.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.OnIdleState.BorderRadius = 1;
            this.mainBttAcerca.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttAcerca.OnIdleState.BorderThickness = 0;
            this.mainBttAcerca.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.OnIdleState.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttAcerca.OnIdleState.IconLeftImage = global::HP3.Properties.Resources.icoInfoWhite;
            this.mainBttAcerca.OnIdleState.IconRightImage = null;
            this.mainBttAcerca.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.OnPressedState.BorderRadius = 1;
            this.mainBttAcerca.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttAcerca.OnPressedState.BorderThickness = 0;
            this.mainBttAcerca.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttAcerca.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttAcerca.OnPressedState.IconLeftImage = global::HP3.Properties.Resources.icoInfoActive;
            this.mainBttAcerca.OnPressedState.IconRightImage = null;
            this.mainBttAcerca.Size = new System.Drawing.Size(185, 40);
            this.mainBttAcerca.TabIndex = 5;
            this.mainBttAcerca.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttAcerca.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mainBttAcerca.TextMarginLeft = 0;
            this.mainBttAcerca.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.mainBttAcerca.UseDefaultRadiusAndThickness = true;
            this.mainBttAcerca.Click += new System.EventHandler(this.mainClickBotones);
            // 
            // mainBttSeguridad
            // 
            this.mainBttSeguridad.AllowAnimations = true;
            this.mainBttSeguridad.AllowMouseEffects = true;
            this.mainBttSeguridad.AllowToggling = true;
            this.mainBttSeguridad.AnimationSpeed = 200;
            this.mainBttSeguridad.AutoGenerateColors = false;
            this.mainBttSeguridad.AutoRoundBorders = false;
            this.mainBttSeguridad.AutoSizeLeftIcon = true;
            this.mainBttSeguridad.AutoSizeRightIcon = true;
            this.mainBttSeguridad.BackColor = System.Drawing.Color.Transparent;
            this.mainBttSeguridad.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainBttSeguridad.BackgroundImage")));
            this.mainBttSeguridad.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttSeguridad.ButtonText = "Seguridad";
            this.mainBttSeguridad.ButtonTextMarginLeft = 0;
            this.mainBttSeguridad.ColorContrastOnClick = 45;
            this.mainBttSeguridad.ColorContrastOnHover = 45;
            this.mainBttSeguridad.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = false;
            borderEdges3.BottomRight = false;
            borderEdges3.TopLeft = false;
            borderEdges3.TopRight = false;
            this.mainBttSeguridad.CustomizableEdges = borderEdges3;
            this.mainBttSeguridad.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mainBttSeguridad.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttSeguridad.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttSeguridad.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttSeguridad.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mainBttSeguridad.Font = new System.Drawing.Font("Urbanist Medium", 13F);
            this.mainBttSeguridad.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttSeguridad.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttSeguridad.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.mainBttSeguridad.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.mainBttSeguridad.IconMarginLeft = 11;
            this.mainBttSeguridad.IconPadding = 8;
            this.mainBttSeguridad.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mainBttSeguridad.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mainBttSeguridad.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mainBttSeguridad.IconSize = 25;
            this.mainBttSeguridad.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.IdleBorderRadius = 1;
            this.mainBttSeguridad.IdleBorderThickness = 1;
            this.mainBttSeguridad.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.IdleIconLeftImage = global::HP3.Properties.Resources.icoSecurityWhite;
            this.mainBttSeguridad.IdleIconRightImage = null;
            this.mainBttSeguridad.IndicateFocus = false;
            this.mainBttSeguridad.Location = new System.Drawing.Point(0, 298);
            this.mainBttSeguridad.Name = "mainBttSeguridad";
            this.mainBttSeguridad.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttSeguridad.OnDisabledState.BorderRadius = 1;
            this.mainBttSeguridad.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttSeguridad.OnDisabledState.BorderThickness = 0;
            this.mainBttSeguridad.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttSeguridad.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttSeguridad.OnDisabledState.IconLeftImage = null;
            this.mainBttSeguridad.OnDisabledState.IconRightImage = null;
            this.mainBttSeguridad.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.onHoverState.BorderRadius = 1;
            this.mainBttSeguridad.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttSeguridad.onHoverState.BorderThickness = 0;
            this.mainBttSeguridad.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttSeguridad.onHoverState.IconLeftImage = null;
            this.mainBttSeguridad.onHoverState.IconRightImage = null;
            this.mainBttSeguridad.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.OnIdleState.BorderRadius = 1;
            this.mainBttSeguridad.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttSeguridad.OnIdleState.BorderThickness = 0;
            this.mainBttSeguridad.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.OnIdleState.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttSeguridad.OnIdleState.IconLeftImage = global::HP3.Properties.Resources.icoSecurityWhite;
            this.mainBttSeguridad.OnIdleState.IconRightImage = null;
            this.mainBttSeguridad.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.OnPressedState.BorderRadius = 1;
            this.mainBttSeguridad.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttSeguridad.OnPressedState.BorderThickness = 0;
            this.mainBttSeguridad.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttSeguridad.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttSeguridad.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.mainBttSeguridad.OnPressedState.IconRightImage = null;
            this.mainBttSeguridad.Size = new System.Drawing.Size(185, 40);
            this.mainBttSeguridad.TabIndex = 4;
            this.mainBttSeguridad.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttSeguridad.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mainBttSeguridad.TextMarginLeft = 0;
            this.mainBttSeguridad.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.mainBttSeguridad.UseDefaultRadiusAndThickness = true;
            this.mainBttSeguridad.Click += new System.EventHandler(this.mainClickBotones);
            // 
            // mainBttFacturacion
            // 
            this.mainBttFacturacion.AllowAnimations = true;
            this.mainBttFacturacion.AllowMouseEffects = true;
            this.mainBttFacturacion.AllowToggling = true;
            this.mainBttFacturacion.AnimationSpeed = 200;
            this.mainBttFacturacion.AutoGenerateColors = false;
            this.mainBttFacturacion.AutoRoundBorders = false;
            this.mainBttFacturacion.AutoSizeLeftIcon = true;
            this.mainBttFacturacion.AutoSizeRightIcon = true;
            this.mainBttFacturacion.BackColor = System.Drawing.Color.Transparent;
            this.mainBttFacturacion.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainBttFacturacion.BackgroundImage")));
            this.mainBttFacturacion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttFacturacion.ButtonText = "Facturacion";
            this.mainBttFacturacion.ButtonTextMarginLeft = 0;
            this.mainBttFacturacion.ColorContrastOnClick = 45;
            this.mainBttFacturacion.ColorContrastOnHover = 45;
            this.mainBttFacturacion.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = false;
            borderEdges4.BottomRight = false;
            borderEdges4.TopLeft = false;
            borderEdges4.TopRight = false;
            this.mainBttFacturacion.CustomizableEdges = borderEdges4;
            this.mainBttFacturacion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mainBttFacturacion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttFacturacion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttFacturacion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttFacturacion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mainBttFacturacion.Font = new System.Drawing.Font("Urbanist Medium", 13F);
            this.mainBttFacturacion.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttFacturacion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttFacturacion.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.mainBttFacturacion.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.mainBttFacturacion.IconMarginLeft = 11;
            this.mainBttFacturacion.IconPadding = 8;
            this.mainBttFacturacion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mainBttFacturacion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mainBttFacturacion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mainBttFacturacion.IconSize = 25;
            this.mainBttFacturacion.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.IdleBorderRadius = 1;
            this.mainBttFacturacion.IdleBorderThickness = 1;
            this.mainBttFacturacion.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.IdleIconLeftImage = global::HP3.Properties.Resources.icoFactWhite;
            this.mainBttFacturacion.IdleIconRightImage = null;
            this.mainBttFacturacion.IndicateFocus = false;
            this.mainBttFacturacion.Location = new System.Drawing.Point(0, 252);
            this.mainBttFacturacion.Name = "mainBttFacturacion";
            this.mainBttFacturacion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttFacturacion.OnDisabledState.BorderRadius = 1;
            this.mainBttFacturacion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttFacturacion.OnDisabledState.BorderThickness = 0;
            this.mainBttFacturacion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttFacturacion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttFacturacion.OnDisabledState.IconLeftImage = null;
            this.mainBttFacturacion.OnDisabledState.IconRightImage = null;
            this.mainBttFacturacion.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.onHoverState.BorderRadius = 1;
            this.mainBttFacturacion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttFacturacion.onHoverState.BorderThickness = 0;
            this.mainBttFacturacion.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttFacturacion.onHoverState.IconLeftImage = null;
            this.mainBttFacturacion.onHoverState.IconRightImage = null;
            this.mainBttFacturacion.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.OnIdleState.BorderRadius = 1;
            this.mainBttFacturacion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttFacturacion.OnIdleState.BorderThickness = 0;
            this.mainBttFacturacion.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.OnIdleState.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttFacturacion.OnIdleState.IconLeftImage = global::HP3.Properties.Resources.icoFactWhite;
            this.mainBttFacturacion.OnIdleState.IconRightImage = null;
            this.mainBttFacturacion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.OnPressedState.BorderRadius = 1;
            this.mainBttFacturacion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttFacturacion.OnPressedState.BorderThickness = 0;
            this.mainBttFacturacion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttFacturacion.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttFacturacion.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.mainBttFacturacion.OnPressedState.IconRightImage = null;
            this.mainBttFacturacion.Size = new System.Drawing.Size(185, 40);
            this.mainBttFacturacion.TabIndex = 3;
            this.mainBttFacturacion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttFacturacion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mainBttFacturacion.TextMarginLeft = 0;
            this.mainBttFacturacion.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.mainBttFacturacion.UseDefaultRadiusAndThickness = true;
            this.mainBttFacturacion.Click += new System.EventHandler(this.mainClickBotones);
            // 
            // indicator
            // 
            this.indicator.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.indicator.Location = new System.Drawing.Point(0, 206);
            this.indicator.Name = "indicator";
            this.indicator.Size = new System.Drawing.Size(3, 40);
            this.indicator.TabIndex = 2;
            this.indicator.TabStop = false;
            // 
            // mainBttTablas
            // 
            this.mainBttTablas.AllowAnimations = true;
            this.mainBttTablas.AllowMouseEffects = true;
            this.mainBttTablas.AllowToggling = true;
            this.mainBttTablas.AnimationSpeed = 200;
            this.mainBttTablas.AutoGenerateColors = false;
            this.mainBttTablas.AutoRoundBorders = false;
            this.mainBttTablas.AutoSizeLeftIcon = true;
            this.mainBttTablas.AutoSizeRightIcon = true;
            this.mainBttTablas.BackColor = System.Drawing.Color.Transparent;
            this.mainBttTablas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainBttTablas.BackgroundImage")));
            this.mainBttTablas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttTablas.ButtonText = "Tablas";
            this.mainBttTablas.ButtonTextMarginLeft = 0;
            this.mainBttTablas.ColorContrastOnClick = 45;
            this.mainBttTablas.ColorContrastOnHover = 45;
            this.mainBttTablas.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = false;
            borderEdges5.BottomRight = false;
            borderEdges5.TopLeft = false;
            borderEdges5.TopRight = false;
            this.mainBttTablas.CustomizableEdges = borderEdges5;
            this.mainBttTablas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mainBttTablas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttTablas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttTablas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttTablas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mainBttTablas.Font = new System.Drawing.Font("Urbanist Medium", 13F);
            this.mainBttTablas.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttTablas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttTablas.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.mainBttTablas.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.mainBttTablas.IconMarginLeft = 11;
            this.mainBttTablas.IconPadding = 8;
            this.mainBttTablas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mainBttTablas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mainBttTablas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mainBttTablas.IconSize = 25;
            this.mainBttTablas.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.IdleBorderRadius = 1;
            this.mainBttTablas.IdleBorderThickness = 1;
            this.mainBttTablas.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.IdleIconLeftImage = global::HP3.Properties.Resources.icoHomeWhite;
            this.mainBttTablas.IdleIconRightImage = null;
            this.mainBttTablas.IndicateFocus = false;
            this.mainBttTablas.Location = new System.Drawing.Point(0, 206);
            this.mainBttTablas.Name = "mainBttTablas";
            this.mainBttTablas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttTablas.OnDisabledState.BorderRadius = 1;
            this.mainBttTablas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttTablas.OnDisabledState.BorderThickness = 0;
            this.mainBttTablas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttTablas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttTablas.OnDisabledState.IconLeftImage = null;
            this.mainBttTablas.OnDisabledState.IconRightImage = null;
            this.mainBttTablas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.onHoverState.BorderRadius = 1;
            this.mainBttTablas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttTablas.onHoverState.BorderThickness = 0;
            this.mainBttTablas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttTablas.onHoverState.IconLeftImage = null;
            this.mainBttTablas.onHoverState.IconRightImage = null;
            this.mainBttTablas.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.OnIdleState.BorderRadius = 1;
            this.mainBttTablas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttTablas.OnIdleState.BorderThickness = 0;
            this.mainBttTablas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.OnIdleState.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttTablas.OnIdleState.IconLeftImage = global::HP3.Properties.Resources.icoHomeWhite;
            this.mainBttTablas.OnIdleState.IconRightImage = null;
            this.mainBttTablas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.OnPressedState.BorderRadius = 1;
            this.mainBttTablas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttTablas.OnPressedState.BorderThickness = 0;
            this.mainBttTablas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttTablas.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttTablas.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage2")));
            this.mainBttTablas.OnPressedState.IconRightImage = null;
            this.mainBttTablas.Size = new System.Drawing.Size(185, 40);
            this.mainBttTablas.TabIndex = 1;
            this.mainBttTablas.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttTablas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mainBttTablas.TextMarginLeft = 0;
            this.mainBttTablas.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.mainBttTablas.UseDefaultRadiusAndThickness = true;
            this.mainBttTablas.Click += new System.EventHandler(this.mainClickBotones);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuPictureBox1.BorderRadius = 50;
            this.bunifuPictureBox1.Image = global::HP3.Properties.Resources.imgUserWhite;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(42, 29);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(100, 100);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // mainBttExit
            // 
            this.mainBttExit.AllowAnimations = true;
            this.mainBttExit.AllowMouseEffects = true;
            this.mainBttExit.AllowToggling = true;
            this.mainBttExit.AnimationSpeed = 200;
            this.mainBttExit.AutoGenerateColors = false;
            this.mainBttExit.AutoRoundBorders = false;
            this.mainBttExit.AutoSizeLeftIcon = true;
            this.mainBttExit.AutoSizeRightIcon = true;
            this.mainBttExit.BackColor = System.Drawing.Color.Transparent;
            this.mainBttExit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainBttExit.BackgroundImage")));
            this.mainBttExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttExit.ButtonText = "Salir";
            this.mainBttExit.ButtonTextMarginLeft = 0;
            this.mainBttExit.ColorContrastOnClick = 45;
            this.mainBttExit.ColorContrastOnHover = 45;
            this.mainBttExit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = false;
            borderEdges1.BottomRight = false;
            borderEdges1.TopLeft = false;
            borderEdges1.TopRight = false;
            this.mainBttExit.CustomizableEdges = borderEdges1;
            this.mainBttExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mainBttExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttExit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mainBttExit.Font = new System.Drawing.Font("Urbanist Medium", 13F);
            this.mainBttExit.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttExit.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.mainBttExit.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.mainBttExit.IconMarginLeft = 11;
            this.mainBttExit.IconPadding = 8;
            this.mainBttExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mainBttExit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mainBttExit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mainBttExit.IconSize = 25;
            this.mainBttExit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.IdleBorderRadius = 1;
            this.mainBttExit.IdleBorderThickness = 1;
            this.mainBttExit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.IdleIconLeftImage = global::HP3.Properties.Resources.icoExitWhite;
            this.mainBttExit.IdleIconRightImage = null;
            this.mainBttExit.IndicateFocus = false;
            this.mainBttExit.Location = new System.Drawing.Point(0, 453);
            this.mainBttExit.Name = "mainBttExit";
            this.mainBttExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mainBttExit.OnDisabledState.BorderRadius = 1;
            this.mainBttExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttExit.OnDisabledState.BorderThickness = 0;
            this.mainBttExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mainBttExit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mainBttExit.OnDisabledState.IconLeftImage = null;
            this.mainBttExit.OnDisabledState.IconRightImage = null;
            this.mainBttExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.onHoverState.BorderRadius = 1;
            this.mainBttExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttExit.onHoverState.BorderThickness = 0;
            this.mainBttExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttExit.onHoverState.IconLeftImage = null;
            this.mainBttExit.onHoverState.IconRightImage = null;
            this.mainBttExit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.OnIdleState.BorderRadius = 1;
            this.mainBttExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttExit.OnIdleState.BorderThickness = 0;
            this.mainBttExit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.OnIdleState.ForeColor = System.Drawing.SystemColors.Control;
            this.mainBttExit.OnIdleState.IconLeftImage = global::HP3.Properties.Resources.icoExitWhite;
            this.mainBttExit.OnIdleState.IconRightImage = null;
            this.mainBttExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.OnPressedState.BorderRadius = 1;
            this.mainBttExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mainBttExit.OnPressedState.BorderThickness = 0;
            this.mainBttExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.mainBttExit.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.mainBttExit.OnPressedState.IconLeftImage = global::HP3.Properties.Resources.icoExitActive;
            this.mainBttExit.OnPressedState.IconRightImage = null;
            this.mainBttExit.Size = new System.Drawing.Size(185, 40);
            this.mainBttExit.TabIndex = 7;
            this.mainBttExit.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mainBttExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mainBttExit.TextMarginLeft = 0;
            this.mainBttExit.TextPadding = new System.Windows.Forms.Padding(45, 0, 0, 0);
            this.mainBttExit.UseDefaultRadiusAndThickness = true;
            this.mainBttExit.Click += new System.EventHandler(this.mainBttExit_Click);
            // 
            // mainPages
            // 
            this.mainPages.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.mainPages.AllowTransitions = false;
            this.mainPages.Controls.Add(this.tabTablas);
            this.mainPages.Controls.Add(this.tabFacturacion);
            this.mainPages.Controls.Add(this.tabSeguridad);
            this.mainPages.Controls.Add(this.tabAcerca);
            this.mainPages.Location = new System.Drawing.Point(0, 0);
            this.mainPages.Multiline = true;
            this.mainPages.Name = "mainPages";
            this.mainPages.Page = this.tabTablas;
            this.mainPages.PageIndex = 0;
            this.mainPages.PageName = "tabTablas";
            this.mainPages.PageTitle = "tablas";
            this.mainPages.SelectedIndex = 0;
            this.mainPages.Size = new System.Drawing.Size(649, 511);
            this.mainPages.TabIndex = 0;
            animation2.AnimateOnlyDifferences = false;
            animation2.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.BlindCoeff")));
            animation2.LeafCoeff = 0F;
            animation2.MaxTime = 1F;
            animation2.MinTime = 0F;
            animation2.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.MosaicCoeff")));
            animation2.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation2.MosaicShift")));
            animation2.MosaicSize = 0;
            animation2.Padding = new System.Windows.Forms.Padding(0);
            animation2.RotateCoeff = 0F;
            animation2.RotateLimit = 0F;
            animation2.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.ScaleCoeff")));
            animation2.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.SlideCoeff")));
            animation2.TimeCoeff = 0F;
            animation2.TransparencyCoeff = 0F;
            this.mainPages.Transition = animation2;
            this.mainPages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabAcerca
            // 
            this.tabAcerca.BackColor = System.Drawing.Color.Tomato;
            this.tabAcerca.Location = new System.Drawing.Point(4, 4);
            this.tabAcerca.Name = "tabAcerca";
            this.tabAcerca.Size = new System.Drawing.Size(641, 485);
            this.tabAcerca.TabIndex = 3;
            this.tabAcerca.Text = "acerca";
            // 
            // tabSeguridad
            // 
            this.tabSeguridad.BackColor = System.Drawing.Color.Violet;
            this.tabSeguridad.Location = new System.Drawing.Point(4, 4);
            this.tabSeguridad.Name = "tabSeguridad";
            this.tabSeguridad.Size = new System.Drawing.Size(641, 485);
            this.tabSeguridad.TabIndex = 2;
            this.tabSeguridad.Text = "seguridad";
            // 
            // tabFacturacion
            // 
            this.tabFacturacion.BackColor = System.Drawing.Color.Turquoise;
            this.tabFacturacion.Location = new System.Drawing.Point(4, 4);
            this.tabFacturacion.Name = "tabFacturacion";
            this.tabFacturacion.Padding = new System.Windows.Forms.Padding(3);
            this.tabFacturacion.Size = new System.Drawing.Size(641, 485);
            this.tabFacturacion.TabIndex = 1;
            this.tabFacturacion.Text = "facturacion";
            // 
            // tabTablas
            // 
            this.tabTablas.BackColor = System.Drawing.Color.Transparent;
            this.tabTablas.Controls.Add(this.tablasPages);
            this.tabTablas.Controls.Add(this.bunifuPanel2);
            this.tabTablas.Location = new System.Drawing.Point(4, 4);
            this.tabTablas.Name = "tabTablas";
            this.tabTablas.Padding = new System.Windows.Forms.Padding(3);
            this.tabTablas.Size = new System.Drawing.Size(641, 485);
            this.tabTablas.TabIndex = 0;
            this.tabTablas.Text = "tablas";
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.mainPages);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(185, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(649, 511);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.tablasBttCategorias);
            this.bunifuPanel2.Controls.Add(this.tablasBttProductos);
            this.bunifuPanel2.Controls.Add(this.tablasBttClientes);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel2.Location = new System.Drawing.Point(3, 3);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(635, 479);
            this.bunifuPanel2.TabIndex = 2;
            // 
            // tablasBttCategorias
            // 
            this.tablasBttCategorias.AllowAnimations = true;
            this.tablasBttCategorias.AllowMouseEffects = true;
            this.tablasBttCategorias.AllowToggling = true;
            this.tablasBttCategorias.AnimationSpeed = 200;
            this.tablasBttCategorias.AutoGenerateColors = false;
            this.tablasBttCategorias.AutoRoundBorders = false;
            this.tablasBttCategorias.AutoSizeLeftIcon = true;
            this.tablasBttCategorias.AutoSizeRightIcon = true;
            this.tablasBttCategorias.BackColor = System.Drawing.Color.Transparent;
            this.tablasBttCategorias.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tablasBttCategorias.BackgroundImage")));
            this.tablasBttCategorias.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttCategorias.ButtonText = "Categorias";
            this.tablasBttCategorias.ButtonTextMarginLeft = 0;
            this.tablasBttCategorias.ColorContrastOnClick = 45;
            this.tablasBttCategorias.ColorContrastOnHover = 45;
            this.tablasBttCategorias.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.tablasBttCategorias.CustomizableEdges = borderEdges6;
            this.tablasBttCategorias.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tablasBttCategorias.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttCategorias.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttCategorias.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttCategorias.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tablasBttCategorias.Font = new System.Drawing.Font("Urbanist", 13F);
            this.tablasBttCategorias.ForeColor = System.Drawing.Color.White;
            this.tablasBttCategorias.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttCategorias.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttCategorias.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tablasBttCategorias.IconMarginLeft = 11;
            this.tablasBttCategorias.IconPadding = 10;
            this.tablasBttCategorias.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tablasBttCategorias.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttCategorias.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tablasBttCategorias.IconSize = 25;
            this.tablasBttCategorias.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.IdleBorderRadius = 30;
            this.tablasBttCategorias.IdleBorderThickness = 1;
            this.tablasBttCategorias.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.IdleIconLeftImage = null;
            this.tablasBttCategorias.IdleIconRightImage = null;
            this.tablasBttCategorias.IndicateFocus = true;
            this.tablasBttCategorias.Location = new System.Drawing.Point(390, 31);
            this.tablasBttCategorias.Name = "tablasBttCategorias";
            this.tablasBttCategorias.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttCategorias.OnDisabledState.BorderRadius = 30;
            this.tablasBttCategorias.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttCategorias.OnDisabledState.BorderThickness = 1;
            this.tablasBttCategorias.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttCategorias.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttCategorias.OnDisabledState.IconLeftImage = null;
            this.tablasBttCategorias.OnDisabledState.IconRightImage = null;
            this.tablasBttCategorias.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.onHoverState.BorderRadius = 30;
            this.tablasBttCategorias.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttCategorias.onHoverState.BorderThickness = 1;
            this.tablasBttCategorias.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.tablasBttCategorias.onHoverState.IconLeftImage = null;
            this.tablasBttCategorias.onHoverState.IconRightImage = null;
            this.tablasBttCategorias.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.OnIdleState.BorderRadius = 30;
            this.tablasBttCategorias.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttCategorias.OnIdleState.BorderThickness = 1;
            this.tablasBttCategorias.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tablasBttCategorias.OnIdleState.IconLeftImage = null;
            this.tablasBttCategorias.OnIdleState.IconRightImage = null;
            this.tablasBttCategorias.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.OnPressedState.BorderRadius = 30;
            this.tablasBttCategorias.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttCategorias.OnPressedState.BorderThickness = 1;
            this.tablasBttCategorias.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttCategorias.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.tablasBttCategorias.OnPressedState.IconLeftImage = null;
            this.tablasBttCategorias.OnPressedState.IconRightImage = null;
            this.tablasBttCategorias.Size = new System.Drawing.Size(140, 35);
            this.tablasBttCategorias.TabIndex = 2;
            this.tablasBttCategorias.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttCategorias.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tablasBttCategorias.TextMarginLeft = 0;
            this.tablasBttCategorias.TextPadding = new System.Windows.Forms.Padding(0);
            this.tablasBttCategorias.UseDefaultRadiusAndThickness = true;
            this.tablasBttCategorias.Click += new System.EventHandler(this.altClickBotones);
            // 
            // tablasBttProductos
            // 
            this.tablasBttProductos.AllowAnimations = true;
            this.tablasBttProductos.AllowMouseEffects = true;
            this.tablasBttProductos.AllowToggling = true;
            this.tablasBttProductos.AnimationSpeed = 200;
            this.tablasBttProductos.AutoGenerateColors = false;
            this.tablasBttProductos.AutoRoundBorders = false;
            this.tablasBttProductos.AutoSizeLeftIcon = true;
            this.tablasBttProductos.AutoSizeRightIcon = true;
            this.tablasBttProductos.BackColor = System.Drawing.Color.Transparent;
            this.tablasBttProductos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tablasBttProductos.BackgroundImage")));
            this.tablasBttProductos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttProductos.ButtonText = "Productos";
            this.tablasBttProductos.ButtonTextMarginLeft = 0;
            this.tablasBttProductos.ColorContrastOnClick = 45;
            this.tablasBttProductos.ColorContrastOnHover = 45;
            this.tablasBttProductos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.tablasBttProductos.CustomizableEdges = borderEdges7;
            this.tablasBttProductos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tablasBttProductos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttProductos.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttProductos.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttProductos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tablasBttProductos.Font = new System.Drawing.Font("Urbanist", 13F);
            this.tablasBttProductos.ForeColor = System.Drawing.Color.White;
            this.tablasBttProductos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttProductos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttProductos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tablasBttProductos.IconMarginLeft = 11;
            this.tablasBttProductos.IconPadding = 10;
            this.tablasBttProductos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tablasBttProductos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttProductos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tablasBttProductos.IconSize = 25;
            this.tablasBttProductos.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.IdleBorderRadius = 30;
            this.tablasBttProductos.IdleBorderThickness = 1;
            this.tablasBttProductos.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.IdleIconLeftImage = null;
            this.tablasBttProductos.IdleIconRightImage = null;
            this.tablasBttProductos.IndicateFocus = true;
            this.tablasBttProductos.Location = new System.Drawing.Point(244, 31);
            this.tablasBttProductos.Name = "tablasBttProductos";
            this.tablasBttProductos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttProductos.OnDisabledState.BorderRadius = 30;
            this.tablasBttProductos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttProductos.OnDisabledState.BorderThickness = 1;
            this.tablasBttProductos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttProductos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttProductos.OnDisabledState.IconLeftImage = null;
            this.tablasBttProductos.OnDisabledState.IconRightImage = null;
            this.tablasBttProductos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.onHoverState.BorderRadius = 30;
            this.tablasBttProductos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttProductos.onHoverState.BorderThickness = 1;
            this.tablasBttProductos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.tablasBttProductos.onHoverState.IconLeftImage = null;
            this.tablasBttProductos.onHoverState.IconRightImage = null;
            this.tablasBttProductos.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.OnIdleState.BorderRadius = 30;
            this.tablasBttProductos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttProductos.OnIdleState.BorderThickness = 1;
            this.tablasBttProductos.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tablasBttProductos.OnIdleState.IconLeftImage = null;
            this.tablasBttProductos.OnIdleState.IconRightImage = null;
            this.tablasBttProductos.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.OnPressedState.BorderRadius = 30;
            this.tablasBttProductos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttProductos.OnPressedState.BorderThickness = 1;
            this.tablasBttProductos.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttProductos.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.tablasBttProductos.OnPressedState.IconLeftImage = null;
            this.tablasBttProductos.OnPressedState.IconRightImage = null;
            this.tablasBttProductos.Size = new System.Drawing.Size(140, 35);
            this.tablasBttProductos.TabIndex = 1;
            this.tablasBttProductos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttProductos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tablasBttProductos.TextMarginLeft = 0;
            this.tablasBttProductos.TextPadding = new System.Windows.Forms.Padding(0);
            this.tablasBttProductos.UseDefaultRadiusAndThickness = true;
            this.tablasBttProductos.Click += new System.EventHandler(this.altClickBotones);
            // 
            // tablasBttClientes
            // 
            this.tablasBttClientes.AllowAnimations = true;
            this.tablasBttClientes.AllowMouseEffects = true;
            this.tablasBttClientes.AllowToggling = true;
            this.tablasBttClientes.AnimationSpeed = 200;
            this.tablasBttClientes.AutoGenerateColors = false;
            this.tablasBttClientes.AutoRoundBorders = false;
            this.tablasBttClientes.AutoSizeLeftIcon = true;
            this.tablasBttClientes.AutoSizeRightIcon = true;
            this.tablasBttClientes.BackColor = System.Drawing.Color.Transparent;
            this.tablasBttClientes.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tablasBttClientes.BackgroundImage")));
            this.tablasBttClientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttClientes.ButtonText = "Clientes";
            this.tablasBttClientes.ButtonTextMarginLeft = 0;
            this.tablasBttClientes.ColorContrastOnClick = 45;
            this.tablasBttClientes.ColorContrastOnHover = 45;
            this.tablasBttClientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.tablasBttClientes.CustomizableEdges = borderEdges8;
            this.tablasBttClientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tablasBttClientes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttClientes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttClientes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttClientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tablasBttClientes.Font = new System.Drawing.Font("Urbanist", 13F);
            this.tablasBttClientes.ForeColor = System.Drawing.Color.White;
            this.tablasBttClientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttClientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttClientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tablasBttClientes.IconMarginLeft = 11;
            this.tablasBttClientes.IconPadding = 10;
            this.tablasBttClientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tablasBttClientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.tablasBttClientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tablasBttClientes.IconSize = 25;
            this.tablasBttClientes.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.IdleBorderRadius = 30;
            this.tablasBttClientes.IdleBorderThickness = 1;
            this.tablasBttClientes.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.IdleIconLeftImage = null;
            this.tablasBttClientes.IdleIconRightImage = null;
            this.tablasBttClientes.IndicateFocus = true;
            this.tablasBttClientes.Location = new System.Drawing.Point(98, 31);
            this.tablasBttClientes.Name = "tablasBttClientes";
            this.tablasBttClientes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tablasBttClientes.OnDisabledState.BorderRadius = 30;
            this.tablasBttClientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttClientes.OnDisabledState.BorderThickness = 1;
            this.tablasBttClientes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tablasBttClientes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tablasBttClientes.OnDisabledState.IconLeftImage = null;
            this.tablasBttClientes.OnDisabledState.IconRightImage = null;
            this.tablasBttClientes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.onHoverState.BorderRadius = 30;
            this.tablasBttClientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttClientes.onHoverState.BorderThickness = 1;
            this.tablasBttClientes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.tablasBttClientes.onHoverState.IconLeftImage = null;
            this.tablasBttClientes.onHoverState.IconRightImage = null;
            this.tablasBttClientes.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.OnIdleState.BorderRadius = 30;
            this.tablasBttClientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttClientes.OnIdleState.BorderThickness = 1;
            this.tablasBttClientes.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tablasBttClientes.OnIdleState.IconLeftImage = null;
            this.tablasBttClientes.OnIdleState.IconRightImage = null;
            this.tablasBttClientes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.OnPressedState.BorderRadius = 30;
            this.tablasBttClientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tablasBttClientes.OnPressedState.BorderThickness = 1;
            this.tablasBttClientes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.tablasBttClientes.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.tablasBttClientes.OnPressedState.IconLeftImage = null;
            this.tablasBttClientes.OnPressedState.IconRightImage = null;
            this.tablasBttClientes.Size = new System.Drawing.Size(140, 35);
            this.tablasBttClientes.TabIndex = 0;
            this.tablasBttClientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tablasBttClientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tablasBttClientes.TextMarginLeft = 0;
            this.tablasBttClientes.TextPadding = new System.Windows.Forms.Padding(0);
            this.tablasBttClientes.UseDefaultRadiusAndThickness = true;
            this.tablasBttClientes.Click += new System.EventHandler(this.altClickBotones);
            // 
            // tablasPages
            // 
            this.tablasPages.Alignment = System.Windows.Forms.TabAlignment.Right;
            this.tablasPages.AllowTransitions = false;
            this.tablasPages.Controls.Add(this.tabClientes);
            this.tablasPages.Controls.Add(this.tabProductos);
            this.tablasPages.Controls.Add(this.tabCategorias);
            this.tablasPages.Location = new System.Drawing.Point(-4, 84);
            this.tablasPages.Multiline = true;
            this.tablasPages.Name = "tablasPages";
            this.tablasPages.Page = this.tabClientes;
            this.tablasPages.PageIndex = 0;
            this.tablasPages.PageName = "tabClientes";
            this.tablasPages.PageTitle = "clientes";
            this.tablasPages.SelectedIndex = 0;
            this.tablasPages.Size = new System.Drawing.Size(659, 423);
            this.tablasPages.TabIndex = 3;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.tablasPages.Transition = animation1;
            this.tablasPages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabClientes
            // 
            this.tabClientes.BackColor = System.Drawing.Color.Wheat;
            this.tabClientes.Location = new System.Drawing.Point(4, 4);
            this.tabClientes.Name = "tabClientes";
            this.tabClientes.Padding = new System.Windows.Forms.Padding(3);
            this.tabClientes.Size = new System.Drawing.Size(632, 415);
            this.tabClientes.TabIndex = 1;
            this.tabClientes.Text = "clientes";
            // 
            // tabProductos
            // 
            this.tabProductos.BackColor = System.Drawing.Color.Teal;
            this.tabProductos.Location = new System.Drawing.Point(4, 4);
            this.tabProductos.Name = "tabProductos";
            this.tabProductos.Size = new System.Drawing.Size(628, 415);
            this.tabProductos.TabIndex = 2;
            this.tabProductos.Text = "Productos";
            // 
            // tabCategorias
            // 
            this.tabCategorias.BackColor = System.Drawing.Color.SpringGreen;
            this.tabCategorias.Location = new System.Drawing.Point(4, 4);
            this.tabCategorias.Name = "tabCategorias";
            this.tabCategorias.Size = new System.Drawing.Size(628, 415);
            this.tabCategorias.TabIndex = 3;
            this.tabCategorias.Text = "Categorias";
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.ClientSize = new System.Drawing.Size(834, 511);
            this.ControlBox = false;
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.mainLeftPanel);
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmMain";
            this.mainLeftPanel.ResumeLayout(false);
            this.mainLeftPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.indicator)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.mainPages.ResumeLayout(false);
            this.tabTablas.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.tablasPages.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel mainLeftPanel;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.PictureBox indicator;
        protected internal Bunifu.UI.WinForms.BunifuButton.BunifuButton mainBttTablas;
        protected internal Bunifu.UI.WinForms.BunifuButton.BunifuButton mainBttAcerca;
        protected internal Bunifu.UI.WinForms.BunifuButton.BunifuButton mainBttSeguridad;
        protected internal Bunifu.UI.WinForms.BunifuButton.BunifuButton mainBttFacturacion;
        private Bunifu.UI.WinForms.BunifuLabel mainLblUserName;
        protected internal Bunifu.UI.WinForms.BunifuButton.BunifuButton mainBttExit;
        private Bunifu.UI.WinForms.BunifuPages mainPages;
        private System.Windows.Forms.TabPage tabTablas;
        private Bunifu.UI.WinForms.BunifuPages tablasPages;
        private System.Windows.Forms.TabPage tabClientes;
        private System.Windows.Forms.TabPage tabProductos;
        private System.Windows.Forms.TabPage tabCategorias;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tablasBttCategorias;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tablasBttProductos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tablasBttClientes;
        private System.Windows.Forms.TabPage tabFacturacion;
        private System.Windows.Forms.TabPage tabSeguridad;
        private System.Windows.Forms.TabPage tabAcerca;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
    }
}