namespace HP3
{
    partial class frmProducto
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmProducto));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblDescripcionP = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblCategoria = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbCategoria = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtbCodigo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtbDescripcion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblID = new Bunifu.UI.WinForms.BunifuLabel();
            this.bttCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtbCantidad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtbNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtbPrecioC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrecioV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bttAñadir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblTittle = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.lblDescripcionP);
            this.bunifuPanel1.Controls.Add(this.lblCategoria);
            this.bunifuPanel1.Controls.Add(this.cbCategoria);
            this.bunifuPanel1.Controls.Add(this.txtbCodigo);
            this.bunifuPanel1.Controls.Add(this.txtbDescripcion);
            this.bunifuPanel1.Controls.Add(this.lblID);
            this.bunifuPanel1.Controls.Add(this.bttCancelar);
            this.bunifuPanel1.Controls.Add(this.txtbCantidad);
            this.bunifuPanel1.Controls.Add(this.txtbNombre);
            this.bunifuPanel1.Controls.Add(this.txtbPrecioC);
            this.bunifuPanel1.Controls.Add(this.txtPrecioV);
            this.bunifuPanel1.Controls.Add(this.bttAñadir);
            this.bunifuPanel1.Controls.Add(this.lblTittle);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(700, 450);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // lblDescripcionP
            // 
            this.lblDescripcionP.AllowParentOverrides = false;
            this.lblDescripcionP.AutoEllipsis = false;
            this.lblDescripcionP.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblDescripcionP.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblDescripcionP.Font = new System.Drawing.Font("Urbanist", 13F);
            this.lblDescripcionP.ForeColor = System.Drawing.Color.Black;
            this.lblDescripcionP.Location = new System.Drawing.Point(380, 205);
            this.lblDescripcionP.Name = "lblDescripcionP";
            this.lblDescripcionP.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDescripcionP.Size = new System.Drawing.Size(186, 22);
            this.lblDescripcionP.TabIndex = 19;
            this.lblDescripcionP.Text = "Descripcion del producto";
            this.lblDescripcionP.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDescripcionP.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblCategoria
            // 
            this.lblCategoria.AllowParentOverrides = false;
            this.lblCategoria.AutoEllipsis = false;
            this.lblCategoria.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblCategoria.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblCategoria.Font = new System.Drawing.Font("Urbanist", 13F);
            this.lblCategoria.ForeColor = System.Drawing.Color.Black;
            this.lblCategoria.Location = new System.Drawing.Point(380, 156);
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCategoria.Size = new System.Drawing.Size(76, 22);
            this.lblCategoria.TabIndex = 18;
            this.lblCategoria.Text = "Categoria";
            this.lblCategoria.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCategoria.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbCategoria
            // 
            this.cbCategoria.BackColor = System.Drawing.Color.Transparent;
            this.cbCategoria.BackgroundColor = System.Drawing.Color.White;
            this.cbCategoria.BorderColor = System.Drawing.Color.Silver;
            this.cbCategoria.BorderRadius = 1;
            this.cbCategoria.Color = System.Drawing.Color.Silver;
            this.cbCategoria.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbCategoria.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbCategoria.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbCategoria.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbCategoria.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbCategoria.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbCategoria.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbCategoria.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbCategoria.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbCategoria.FillDropDown = true;
            this.cbCategoria.FillIndicator = false;
            this.cbCategoria.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbCategoria.Font = new System.Drawing.Font("Urbanist", 12F);
            this.cbCategoria.ForeColor = System.Drawing.Color.Black;
            this.cbCategoria.FormattingEnabled = true;
            this.cbCategoria.Icon = null;
            this.cbCategoria.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbCategoria.IndicatorColor = System.Drawing.Color.Gray;
            this.cbCategoria.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbCategoria.ItemBackColor = System.Drawing.Color.White;
            this.cbCategoria.ItemBorderColor = System.Drawing.Color.White;
            this.cbCategoria.ItemForeColor = System.Drawing.Color.Black;
            this.cbCategoria.ItemHeight = 25;
            this.cbCategoria.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.cbCategoria.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbCategoria.Items.AddRange(new object[] {
            "Cliente",
            "Valor",
            "Emision",
            "Fecha",
            "ID"});
            this.cbCategoria.ItemTopMargin = 3;
            this.cbCategoria.Location = new System.Drawing.Point(473, 152);
            this.cbCategoria.Name = "cbCategoria";
            this.cbCategoria.Size = new System.Drawing.Size(177, 31);
            this.cbCategoria.TabIndex = 15;
            this.cbCategoria.Text = null;
            this.cbCategoria.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbCategoria.TextLeftMargin = 5;
            // 
            // txtbCodigo
            // 
            this.txtbCodigo.AcceptsReturn = false;
            this.txtbCodigo.AcceptsTab = false;
            this.txtbCodigo.AnimationSpeed = 200;
            this.txtbCodigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbCodigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbCodigo.BackColor = System.Drawing.SystemColors.Control;
            this.txtbCodigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbCodigo.BackgroundImage")));
            this.txtbCodigo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtbCodigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtbCodigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtbCodigo.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtbCodigo.BorderRadius = 20;
            this.txtbCodigo.BorderThickness = 1;
            this.txtbCodigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbCodigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCodigo.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtbCodigo.DefaultText = "";
            this.txtbCodigo.FillColor = System.Drawing.Color.White;
            this.txtbCodigo.ForeColor = System.Drawing.Color.Black;
            this.txtbCodigo.HideSelection = true;
            this.txtbCodigo.IconLeft = null;
            this.txtbCodigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCodigo.IconPadding = 10;
            this.txtbCodigo.IconRight = null;
            this.txtbCodigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCodigo.Lines = new string[0];
            this.txtbCodigo.Location = new System.Drawing.Point(70, 185);
            this.txtbCodigo.Margin = new System.Windows.Forms.Padding(0);
            this.txtbCodigo.MaxLength = 32767;
            this.txtbCodigo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbCodigo.Modified = false;
            this.txtbCodigo.Multiline = false;
            this.txtbCodigo.Name = "txtbCodigo";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCodigo.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbCodigo.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCodigo.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCodigo.OnIdleState = stateProperties4;
            this.txtbCodigo.Padding = new System.Windows.Forms.Padding(2);
            this.txtbCodigo.PasswordChar = '\0';
            this.txtbCodigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbCodigo.PlaceholderText = "Codigo";
            this.txtbCodigo.ReadOnly = false;
            this.txtbCodigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbCodigo.SelectedText = "";
            this.txtbCodigo.SelectionLength = 0;
            this.txtbCodigo.SelectionStart = 0;
            this.txtbCodigo.ShortcutsEnabled = true;
            this.txtbCodigo.Size = new System.Drawing.Size(250, 35);
            this.txtbCodigo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbCodigo.TabIndex = 14;
            this.txtbCodigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbCodigo.TextMarginBottom = 0;
            this.txtbCodigo.TextMarginLeft = 3;
            this.txtbCodigo.TextMarginTop = -1;
            this.txtbCodigo.TextPlaceholder = "Codigo";
            this.txtbCodigo.UseSystemPasswordChar = false;
            this.txtbCodigo.WordWrap = true;
            // 
            // txtbDescripcion
            // 
            this.txtbDescripcion.AcceptsReturn = false;
            this.txtbDescripcion.AcceptsTab = false;
            this.txtbDescripcion.AnimationSpeed = 200;
            this.txtbDescripcion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbDescripcion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbDescripcion.BackColor = System.Drawing.SystemColors.Control;
            this.txtbDescripcion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbDescripcion.BackgroundImage")));
            this.txtbDescripcion.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtbDescripcion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtbDescripcion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtbDescripcion.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtbDescripcion.BorderRadius = 20;
            this.txtbDescripcion.BorderThickness = 1;
            this.txtbDescripcion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbDescripcion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbDescripcion.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtbDescripcion.DefaultText = "";
            this.txtbDescripcion.FillColor = System.Drawing.Color.White;
            this.txtbDescripcion.ForeColor = System.Drawing.Color.Black;
            this.txtbDescripcion.HideSelection = true;
            this.txtbDescripcion.IconLeft = null;
            this.txtbDescripcion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbDescripcion.IconPadding = 10;
            this.txtbDescripcion.IconRight = null;
            this.txtbDescripcion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbDescripcion.Lines = new string[0];
            this.txtbDescripcion.Location = new System.Drawing.Point(380, 230);
            this.txtbDescripcion.Margin = new System.Windows.Forms.Padding(0);
            this.txtbDescripcion.MaxLength = 32767;
            this.txtbDescripcion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbDescripcion.Modified = false;
            this.txtbDescripcion.Multiline = true;
            this.txtbDescripcion.Name = "txtbDescripcion";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbDescripcion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbDescripcion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbDescripcion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbDescripcion.OnIdleState = stateProperties8;
            this.txtbDescripcion.Padding = new System.Windows.Forms.Padding(2);
            this.txtbDescripcion.PasswordChar = '\0';
            this.txtbDescripcion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbDescripcion.PlaceholderText = "Descripcion";
            this.txtbDescripcion.ReadOnly = false;
            this.txtbDescripcion.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtbDescripcion.SelectedText = "";
            this.txtbDescripcion.SelectionLength = 0;
            this.txtbDescripcion.SelectionStart = 0;
            this.txtbDescripcion.ShortcutsEnabled = true;
            this.txtbDescripcion.Size = new System.Drawing.Size(270, 95);
            this.txtbDescripcion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbDescripcion.TabIndex = 13;
            this.txtbDescripcion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbDescripcion.TextMarginBottom = 0;
            this.txtbDescripcion.TextMarginLeft = 3;
            this.txtbDescripcion.TextMarginTop = 3;
            this.txtbDescripcion.TextPlaceholder = "Descripcion";
            this.txtbDescripcion.UseSystemPasswordChar = false;
            this.txtbDescripcion.WordWrap = true;
            // 
            // lblID
            // 
            this.lblID.AllowParentOverrides = false;
            this.lblID.AutoEllipsis = false;
            this.lblID.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblID.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblID.Font = new System.Drawing.Font("Urbanist SemiBold", 10F);
            this.lblID.Location = new System.Drawing.Point(85, 116);
            this.lblID.Name = "lblID";
            this.lblID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblID.Size = new System.Drawing.Size(15, 17);
            this.lblID.TabIndex = 12;
            this.lblID.Text = "ID: ";
            this.lblID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bttCancelar
            // 
            this.bttCancelar.AllowAnimations = true;
            this.bttCancelar.AllowMouseEffects = true;
            this.bttCancelar.AllowToggling = true;
            this.bttCancelar.AnimationSpeed = 200;
            this.bttCancelar.AutoGenerateColors = false;
            this.bttCancelar.AutoRoundBorders = false;
            this.bttCancelar.AutoSizeLeftIcon = true;
            this.bttCancelar.AutoSizeRightIcon = true;
            this.bttCancelar.BackColor = System.Drawing.Color.Transparent;
            this.bttCancelar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttCancelar.BackgroundImage")));
            this.bttCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttCancelar.ButtonText = "Cancelar";
            this.bttCancelar.ButtonTextMarginLeft = 0;
            this.bttCancelar.ColorContrastOnClick = 45;
            this.bttCancelar.ColorContrastOnHover = 45;
            this.bttCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bttCancelar.CustomizableEdges = borderEdges1;
            this.bttCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bttCancelar.Font = new System.Drawing.Font("Urbanist", 12F);
            this.bttCancelar.ForeColor = System.Drawing.Color.White;
            this.bttCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bttCancelar.IconMarginLeft = 11;
            this.bttCancelar.IconPadding = 10;
            this.bttCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bttCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bttCancelar.IconSize = 25;
            this.bttCancelar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttCancelar.IdleBorderRadius = 20;
            this.bttCancelar.IdleBorderThickness = 1;
            this.bttCancelar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttCancelar.IdleIconLeftImage = null;
            this.bttCancelar.IdleIconRightImage = null;
            this.bttCancelar.IndicateFocus = true;
            this.bttCancelar.Location = new System.Drawing.Point(380, 328);
            this.bttCancelar.Name = "bttCancelar";
            this.bttCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttCancelar.OnDisabledState.BorderRadius = 20;
            this.bttCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttCancelar.OnDisabledState.BorderThickness = 1;
            this.bttCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttCancelar.OnDisabledState.IconLeftImage = null;
            this.bttCancelar.OnDisabledState.IconRightImage = null;
            this.bttCancelar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.bttCancelar.onHoverState.BorderRadius = 20;
            this.bttCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttCancelar.onHoverState.BorderThickness = 1;
            this.bttCancelar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.bttCancelar.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.bttCancelar.onHoverState.IconLeftImage = null;
            this.bttCancelar.onHoverState.IconRightImage = null;
            this.bttCancelar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttCancelar.OnIdleState.BorderRadius = 20;
            this.bttCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttCancelar.OnIdleState.BorderThickness = 1;
            this.bttCancelar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bttCancelar.OnIdleState.IconLeftImage = null;
            this.bttCancelar.OnIdleState.IconRightImage = null;
            this.bttCancelar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.bttCancelar.OnPressedState.BorderRadius = 20;
            this.bttCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttCancelar.OnPressedState.BorderThickness = 1;
            this.bttCancelar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.bttCancelar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.bttCancelar.OnPressedState.IconLeftImage = null;
            this.bttCancelar.OnPressedState.IconRightImage = null;
            this.bttCancelar.Size = new System.Drawing.Size(100, 30);
            this.bttCancelar.TabIndex = 11;
            this.bttCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttCancelar.TextMarginLeft = 0;
            this.bttCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.bttCancelar.UseDefaultRadiusAndThickness = true;
            this.bttCancelar.Click += new System.EventHandler(this.bttCancelar_Click);
            // 
            // txtbCantidad
            // 
            this.txtbCantidad.AcceptsReturn = false;
            this.txtbCantidad.AcceptsTab = false;
            this.txtbCantidad.AnimationSpeed = 200;
            this.txtbCantidad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbCantidad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbCantidad.BackColor = System.Drawing.SystemColors.Control;
            this.txtbCantidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbCantidad.BackgroundImage")));
            this.txtbCantidad.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtbCantidad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtbCantidad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtbCantidad.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtbCantidad.BorderRadius = 20;
            this.txtbCantidad.BorderThickness = 1;
            this.txtbCantidad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbCantidad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCantidad.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtbCantidad.DefaultText = "";
            this.txtbCantidad.FillColor = System.Drawing.Color.White;
            this.txtbCantidad.ForeColor = System.Drawing.Color.Black;
            this.txtbCantidad.HideSelection = true;
            this.txtbCantidad.IconLeft = null;
            this.txtbCantidad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCantidad.IconPadding = 10;
            this.txtbCantidad.IconRight = null;
            this.txtbCantidad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbCantidad.Lines = new string[0];
            this.txtbCantidad.Location = new System.Drawing.Point(70, 290);
            this.txtbCantidad.Margin = new System.Windows.Forms.Padding(0);
            this.txtbCantidad.MaxLength = 32767;
            this.txtbCantidad.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbCantidad.Modified = false;
            this.txtbCantidad.Multiline = false;
            this.txtbCantidad.Name = "txtbCantidad";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCantidad.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbCantidad.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCantidad.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbCantidad.OnIdleState = stateProperties12;
            this.txtbCantidad.Padding = new System.Windows.Forms.Padding(2);
            this.txtbCantidad.PasswordChar = '\0';
            this.txtbCantidad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbCantidad.PlaceholderText = "Cantidad";
            this.txtbCantidad.ReadOnly = false;
            this.txtbCantidad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbCantidad.SelectedText = "";
            this.txtbCantidad.SelectionLength = 0;
            this.txtbCantidad.SelectionStart = 0;
            this.txtbCantidad.ShortcutsEnabled = true;
            this.txtbCantidad.Size = new System.Drawing.Size(250, 35);
            this.txtbCantidad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbCantidad.TabIndex = 10;
            this.txtbCantidad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbCantidad.TextMarginBottom = 0;
            this.txtbCantidad.TextMarginLeft = 3;
            this.txtbCantidad.TextMarginTop = -1;
            this.txtbCantidad.TextPlaceholder = "Cantidad";
            this.txtbCantidad.UseSystemPasswordChar = false;
            this.txtbCantidad.WordWrap = true;
            // 
            // txtbNombre
            // 
            this.txtbNombre.AcceptsReturn = false;
            this.txtbNombre.AcceptsTab = false;
            this.txtbNombre.AnimationSpeed = 200;
            this.txtbNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbNombre.BackColor = System.Drawing.SystemColors.Control;
            this.txtbNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbNombre.BackgroundImage")));
            this.txtbNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtbNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtbNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtbNombre.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtbNombre.BorderRadius = 20;
            this.txtbNombre.BorderThickness = 1;
            this.txtbNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbNombre.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtbNombre.DefaultText = "";
            this.txtbNombre.FillColor = System.Drawing.Color.White;
            this.txtbNombre.ForeColor = System.Drawing.Color.Black;
            this.txtbNombre.HideSelection = true;
            this.txtbNombre.IconLeft = null;
            this.txtbNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbNombre.IconPadding = 10;
            this.txtbNombre.IconRight = null;
            this.txtbNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbNombre.Lines = new string[0];
            this.txtbNombre.Location = new System.Drawing.Point(70, 150);
            this.txtbNombre.Margin = new System.Windows.Forms.Padding(0);
            this.txtbNombre.MaxLength = 32767;
            this.txtbNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbNombre.Modified = false;
            this.txtbNombre.Multiline = false;
            this.txtbNombre.Name = "txtbNombre";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbNombre.OnIdleState = stateProperties16;
            this.txtbNombre.Padding = new System.Windows.Forms.Padding(2);
            this.txtbNombre.PasswordChar = '\0';
            this.txtbNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbNombre.PlaceholderText = "Nombre";
            this.txtbNombre.ReadOnly = false;
            this.txtbNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbNombre.SelectedText = "";
            this.txtbNombre.SelectionLength = 0;
            this.txtbNombre.SelectionStart = 0;
            this.txtbNombre.ShortcutsEnabled = true;
            this.txtbNombre.Size = new System.Drawing.Size(250, 35);
            this.txtbNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbNombre.TabIndex = 9;
            this.txtbNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbNombre.TextMarginBottom = 0;
            this.txtbNombre.TextMarginLeft = 3;
            this.txtbNombre.TextMarginTop = -1;
            this.txtbNombre.TextPlaceholder = "Nombre";
            this.txtbNombre.UseSystemPasswordChar = false;
            this.txtbNombre.WordWrap = true;
            // 
            // txtbPrecioC
            // 
            this.txtbPrecioC.AcceptsReturn = false;
            this.txtbPrecioC.AcceptsTab = false;
            this.txtbPrecioC.AnimationSpeed = 200;
            this.txtbPrecioC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbPrecioC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbPrecioC.BackColor = System.Drawing.SystemColors.Control;
            this.txtbPrecioC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbPrecioC.BackgroundImage")));
            this.txtbPrecioC.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtbPrecioC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtbPrecioC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtbPrecioC.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtbPrecioC.BorderRadius = 20;
            this.txtbPrecioC.BorderThickness = 1;
            this.txtbPrecioC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbPrecioC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbPrecioC.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtbPrecioC.DefaultText = "";
            this.txtbPrecioC.FillColor = System.Drawing.Color.White;
            this.txtbPrecioC.ForeColor = System.Drawing.Color.Black;
            this.txtbPrecioC.HideSelection = true;
            this.txtbPrecioC.IconLeft = null;
            this.txtbPrecioC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbPrecioC.IconPadding = 10;
            this.txtbPrecioC.IconRight = null;
            this.txtbPrecioC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbPrecioC.Lines = new string[0];
            this.txtbPrecioC.Location = new System.Drawing.Point(70, 220);
            this.txtbPrecioC.Margin = new System.Windows.Forms.Padding(0);
            this.txtbPrecioC.MaxLength = 32767;
            this.txtbPrecioC.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbPrecioC.Modified = false;
            this.txtbPrecioC.Multiline = false;
            this.txtbPrecioC.Name = "txtbPrecioC";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbPrecioC.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbPrecioC.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbPrecioC.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbPrecioC.OnIdleState = stateProperties20;
            this.txtbPrecioC.Padding = new System.Windows.Forms.Padding(2);
            this.txtbPrecioC.PasswordChar = '\0';
            this.txtbPrecioC.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbPrecioC.PlaceholderText = "Precio compra";
            this.txtbPrecioC.ReadOnly = false;
            this.txtbPrecioC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbPrecioC.SelectedText = "";
            this.txtbPrecioC.SelectionLength = 0;
            this.txtbPrecioC.SelectionStart = 0;
            this.txtbPrecioC.ShortcutsEnabled = true;
            this.txtbPrecioC.Size = new System.Drawing.Size(250, 35);
            this.txtbPrecioC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbPrecioC.TabIndex = 8;
            this.txtbPrecioC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbPrecioC.TextMarginBottom = 0;
            this.txtbPrecioC.TextMarginLeft = 3;
            this.txtbPrecioC.TextMarginTop = -1;
            this.txtbPrecioC.TextPlaceholder = "Precio compra";
            this.txtbPrecioC.UseSystemPasswordChar = false;
            this.txtbPrecioC.WordWrap = true;
            // 
            // txtPrecioV
            // 
            this.txtPrecioV.AcceptsReturn = false;
            this.txtPrecioV.AcceptsTab = false;
            this.txtPrecioV.AnimationSpeed = 200;
            this.txtPrecioV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrecioV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrecioV.BackColor = System.Drawing.SystemColors.Control;
            this.txtPrecioV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrecioV.BackgroundImage")));
            this.txtPrecioV.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.txtPrecioV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.txtPrecioV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.txtPrecioV.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.txtPrecioV.BorderRadius = 20;
            this.txtPrecioV.BorderThickness = 1;
            this.txtPrecioV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrecioV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecioV.DefaultFont = new System.Drawing.Font("Urbanist", 12F);
            this.txtPrecioV.DefaultText = "";
            this.txtPrecioV.FillColor = System.Drawing.Color.White;
            this.txtPrecioV.ForeColor = System.Drawing.Color.Black;
            this.txtPrecioV.HideSelection = true;
            this.txtPrecioV.IconLeft = null;
            this.txtPrecioV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecioV.IconPadding = 10;
            this.txtPrecioV.IconRight = null;
            this.txtPrecioV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecioV.Lines = new string[0];
            this.txtPrecioV.Location = new System.Drawing.Point(70, 255);
            this.txtPrecioV.Margin = new System.Windows.Forms.Padding(0);
            this.txtPrecioV.MaxLength = 32767;
            this.txtPrecioV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrecioV.Modified = false;
            this.txtPrecioV.Multiline = false;
            this.txtPrecioV.Name = "txtPrecioV";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecioV.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrecioV.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecioV.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecioV.OnIdleState = stateProperties24;
            this.txtPrecioV.Padding = new System.Windows.Forms.Padding(2);
            this.txtPrecioV.PasswordChar = '\0';
            this.txtPrecioV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrecioV.PlaceholderText = "Precio venta";
            this.txtPrecioV.ReadOnly = false;
            this.txtPrecioV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrecioV.SelectedText = "";
            this.txtPrecioV.SelectionLength = 0;
            this.txtPrecioV.SelectionStart = 0;
            this.txtPrecioV.ShortcutsEnabled = true;
            this.txtPrecioV.Size = new System.Drawing.Size(250, 35);
            this.txtPrecioV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrecioV.TabIndex = 7;
            this.txtPrecioV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrecioV.TextMarginBottom = 0;
            this.txtPrecioV.TextMarginLeft = 3;
            this.txtPrecioV.TextMarginTop = -1;
            this.txtPrecioV.TextPlaceholder = "Precio venta";
            this.txtPrecioV.UseSystemPasswordChar = false;
            this.txtPrecioV.WordWrap = true;
            // 
            // bttAñadir
            // 
            this.bttAñadir.AllowAnimations = true;
            this.bttAñadir.AllowMouseEffects = true;
            this.bttAñadir.AllowToggling = true;
            this.bttAñadir.AnimationSpeed = 200;
            this.bttAñadir.AutoGenerateColors = false;
            this.bttAñadir.AutoRoundBorders = false;
            this.bttAñadir.AutoSizeLeftIcon = true;
            this.bttAñadir.AutoSizeRightIcon = true;
            this.bttAñadir.BackColor = System.Drawing.Color.Transparent;
            this.bttAñadir.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttAñadir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttAñadir.BackgroundImage")));
            this.bttAñadir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttAñadir.ButtonText = "Añadir";
            this.bttAñadir.ButtonTextMarginLeft = 0;
            this.bttAñadir.ColorContrastOnClick = 45;
            this.bttAñadir.ColorContrastOnHover = 45;
            this.bttAñadir.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bttAñadir.CustomizableEdges = borderEdges2;
            this.bttAñadir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttAñadir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttAñadir.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttAñadir.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttAñadir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bttAñadir.Font = new System.Drawing.Font("Urbanist", 12F);
            this.bttAñadir.ForeColor = System.Drawing.Color.White;
            this.bttAñadir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttAñadir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttAñadir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bttAñadir.IconMarginLeft = 11;
            this.bttAñadir.IconPadding = 10;
            this.bttAñadir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bttAñadir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttAñadir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bttAñadir.IconSize = 25;
            this.bttAñadir.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttAñadir.IdleBorderRadius = 20;
            this.bttAñadir.IdleBorderThickness = 1;
            this.bttAñadir.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttAñadir.IdleIconLeftImage = null;
            this.bttAñadir.IdleIconRightImage = null;
            this.bttAñadir.IndicateFocus = true;
            this.bttAñadir.Location = new System.Drawing.Point(220, 328);
            this.bttAñadir.Name = "bttAñadir";
            this.bttAñadir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttAñadir.OnDisabledState.BorderRadius = 20;
            this.bttAñadir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttAñadir.OnDisabledState.BorderThickness = 1;
            this.bttAñadir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttAñadir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttAñadir.OnDisabledState.IconLeftImage = null;
            this.bttAñadir.OnDisabledState.IconRightImage = null;
            this.bttAñadir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.bttAñadir.onHoverState.BorderRadius = 20;
            this.bttAñadir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttAñadir.onHoverState.BorderThickness = 1;
            this.bttAñadir.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(61)))), ((int)(((byte)(122)))));
            this.bttAñadir.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.bttAñadir.onHoverState.IconLeftImage = null;
            this.bttAñadir.onHoverState.IconRightImage = null;
            this.bttAñadir.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttAñadir.OnIdleState.BorderRadius = 20;
            this.bttAñadir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttAñadir.OnIdleState.BorderThickness = 1;
            this.bttAñadir.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(13)))), ((int)(((byte)(37)))));
            this.bttAñadir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bttAñadir.OnIdleState.IconLeftImage = null;
            this.bttAñadir.OnIdleState.IconRightImage = null;
            this.bttAñadir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.bttAñadir.OnPressedState.BorderRadius = 20;
            this.bttAñadir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttAñadir.OnPressedState.BorderThickness = 1;
            this.bttAñadir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(168)))), ((int)(((byte)(216)))));
            this.bttAñadir.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.bttAñadir.OnPressedState.IconLeftImage = null;
            this.bttAñadir.OnPressedState.IconRightImage = null;
            this.bttAñadir.Size = new System.Drawing.Size(100, 30);
            this.bttAñadir.TabIndex = 6;
            this.bttAñadir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttAñadir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttAñadir.TextMarginLeft = 0;
            this.bttAñadir.TextPadding = new System.Windows.Forms.Padding(0);
            this.bttAñadir.UseDefaultRadiusAndThickness = true;
            this.bttAñadir.Click += new System.EventHandler(this.bttAñadir_Click);
            // 
            // lblTittle
            // 
            this.lblTittle.AllowParentOverrides = false;
            this.lblTittle.AutoEllipsis = false;
            this.lblTittle.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTittle.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTittle.Font = new System.Drawing.Font("Urbanist", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTittle.Location = new System.Drawing.Point(205, 57);
            this.lblTittle.Name = "lblTittle";
            this.lblTittle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTittle.Size = new System.Drawing.Size(247, 43);
            this.lblTittle.TabIndex = 0;
            this.lblTittle.Text = "Añadir producto";
            this.lblTittle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTittle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmProducto
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(700, 450);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmProducto";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmCliente";
            this.TopMost = true;
            this.Load += new System.EventHandler(this.frmCliente_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel lblTittle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bttAñadir;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrecioV;
        private Bunifu.UI.WinForms.BunifuTextBox txtbCantidad;
        private Bunifu.UI.WinForms.BunifuTextBox txtbNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtbPrecioC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bttCancelar;
        private Bunifu.UI.WinForms.BunifuLabel lblID;
        private Bunifu.UI.WinForms.BunifuTextBox txtbDescripcion;
        private Bunifu.UI.WinForms.BunifuTextBox txtbCodigo;
        private Bunifu.UI.WinForms.BunifuDropdown cbCategoria;
        private Bunifu.UI.WinForms.BunifuLabel lblCategoria;
        private Bunifu.UI.WinForms.BunifuLabel lblDescripcionP;
    }
}